# Introduction to Python Matrices and NumPy #

In [33]:
import numpy as np
one_dimensional_arr = np.array([0.5,"a",25])
print (one_dimensional_arr)

['0.5' 'a' '25']


In [5]:
# Create and print a numpy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [10]:
# Create an array with 3 elements, starting from default number 0.
b = np.arange(3)
print(b)

[0 1 2]


In [11]:
# Create an array that starts from integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


In [17]:
lin_spaced_arr = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr)

[  0  25  50  75 100]


In [18]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [22]:
char_arr = np.array(['Welcome to Math for ML and DS!'])
print(char_arr)
print(char_arr.dtype) # Prints the data type of the array

['Welcome to Math for ML and DS!']
<U30


In [23]:
# Create a 2x3 array of ones
ones_array = np.ones((2, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


2. numpy.zeros()
Purpose: Creates a new array where all elements are set to 0.

Arguments:

shape: A tuple defining the dimensions of the array.
dtype: Optional; specifies the data type of the array elements.


2. numpy.zeros()
Purpose: Creates a new array where all elements are set to 0.

Arguments:

shape: A tuple defining the dimensions of the array.
dtype: Optional; specifies the data type of the array elements.

In [26]:
# Create a 4x4 array of zeros
zeros_array = np.zeros((4, 4), dtype=int)
print(zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [29]:
# Return a new array with 3 elements without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


4. numpy.random.rand()
Purpose: Creates a new array with random values sampled from a uniform distribution over the interval [0, 1).

Arguments:

Dimensions of the array (specified directly as arguments, not in a tuple).

In [30]:
# Create a 3x3 array with random values
random_array = np.random.rand(3, 3)
print(random_array)

[[0.68021862 0.99476551 0.83973777]
 [0.09336887 0.90129346 0.69182717]
 [0.24579581 0.40034446 0.9003495 ]]


#  Multidimensional Arrays #